; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +hWndhMainWnd
Gui Add, DropDownList, x22 y32 w176, DropDownList||
Gui Add, GroupBox, x9 y8 w202 h65, Select Item Number
Gui Add, CheckBox, x10 y82 w200 h23 +Checked vcheck gcheckBox, Included Configuration Step
Gui Add, GroupBox, x9 y112 w202 h188, Process
Gui Add, Button, x70 y307 w80 h23 gmainStart, &START
Gui Font,, Consolas
Gui Add, Text, x64 y129 w136 h21 +0x200 vloadConfig, Load Configuration
Gui Font
Gui Font,, Consolas
Gui Add, Text, x64 y151 w136 h21 +0x200 vreAfterConfig, Rebooted After Config
Gui Font
Gui Add, Text, x17 y174 w189 h2 +0x10
Gui Font, c0x000000, Consolas
Gui Add, Text, hWndhTxtCheckEthernetPort3 x64 y178 w136 h21 +0x200, Check Ethernet Port
Gui Font
Gui Font,, Consolas
Gui Add, Text, x64 y222 w136 h21 +0x200, Check Temperature
Gui Font
Gui Font,, Consolas
Gui Add, Text, x64 y244 w136 h21 +0x200, Check SIM/ Cellular
Gui Font
Gui Font,, Consolas
Gui Add, Text, x64 y266 w136 h21 +0x200, Check WiFi/ Bluetooth
Gui Font
Gui Font,, Consolas
Gui Add, Text, x64 y200 w136 h21 +0x200, Check LED
Gui Font
Gui Font, c0x00FF00, Ms Shell Dlg 2
Gui Add, Text, x30 y129 w12 h21 +0x200 vcheck1, ✔
Gui Font
Gui Font, c0xFF0000, Ms Shell Dlg 2
Gui Add, Text, x30 y222 w12 h21 +0x200, ✘
Gui Font
Gui Font, c0x808000, Ms Shell Dlg 2
Gui Add, Text, x30 y266 w12 h21 +0x200, ➜
Gui Font
Gui Font, c0x00FF00, Ms Shell Dlg 2
Gui Add, Text, x30 y151 w12 h21 +0x200, ✔
Gui Font
Gui Font, c0x00FF00, Ms Shell Dlg 2
Gui Add, Text, x30 y178 w12 h21 +0x200, ✔
Gui Font
Gui Font, c0x00FF00, Ms Shell Dlg 2
Gui Add, Text, x30 y200 w12 h21 +0x200, ✔
Gui Font
Gui Font, c0x00FF00, Ms Shell Dlg 2
Gui Add, Text, x30 y244 w12 h21 +0x200, ✔
Gui Font

Gui Show, x1269 y324 w220 h340, All MTCDT Auto-Tester
Return

GuiEscape:
GuiClose:
    ExitApp

mainStart() {
    GuiControl Hide, check1
}

checkBox() {
    MsgBox 0, 0, Check run %check%
    if (check = 0) {
        MsgBox 0, 0, Check 0
        GuiControl Disable, loadConfig
    }
}