; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, GroupBox, x9 y10 w222 h190, Enter Values
Gui Font, s10
Gui Add, Text, x17 y34 w55 h21, Serial #:
Gui Add, Text, x17 y59 w55 h21, IMEI #:
Gui Add, Text, x17 y84 w60 h21, NodeID #:
Gui Add, Text, x17 y109 w55 h21, UUID #:
Gui Add, Text, x17 y144 w55 h21, LORA #:
Gui Add, Text, x17 y170 w55 h21, WiFi #:
Gui Font
Gui Add, Text, x22 y135 w198 h2 +0x10 ;;--------------------------
Gui Add, Edit, x79 y32 w145 h21
Gui Add, Edit, x79 y57 w145 h21
Gui Add, Edit, x79 y82 w145 h21
Gui Add, Edit, x79 y107 w145 h21
Gui Add, Edit, x79 y142 w145 h21
Gui Add, Edit, x79 y168 w145 h21

;Gui, Add, TreeView
;P1 := TV_Add("240L")
;P1C1 := TV_Add("Parent 1's first child", P1)  ; Specify P1 to be this item's parent.

;P2 := TV_Add("246L")
;P2C1 := TV_Add("Parent 2's first child", P2)
;P2C2 := TV_Add("Parent 2's second child", P2)

;P3 := TV_Add("247L")
;P3C1 := TV_Add("Parent 2's second child", P3)

Gui Show, w240 h420, Window
Return

GuiEscape:
GuiClose:
    ExitApp
~Enter::
Send {Tab}
