; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, DropDownList, x16 y24 w193, mLinux 4.1.9 WiFi|mLinux 4.1.9 NO Wifi
Gui Add, GroupBox, x7 y1 w209 h61, Select Firmware Version
Gui Add, CheckBox, x9 y70 w207 h23, Included Re-Program Step
Gui Add, ComboBox, x63 y129 w120, Blue|Green

Gui Show, w224 h172, Window
Return

GuiEscape:
GuiClose:
    ExitApp
